javac -d . Styles.java
javac -d . PrivateDB.java
javac -d . UserDBUtilities.java
javac -d . ErrorDialog.java
javac -d . Encryption.java
javac -d . ActionCnfm.java
javac -d . SignUp.java
javac -d . CompleteView.java
javac -d . ListItem.java
javac -d . NewPassword.java
javac -d . ChangeProperty.java
javac -d . Home.java
javac -d .  LogIn.java
java -cp ".;lib/sqlite-jdbc-3.32.3.2.jar" java_miniproject.LogIn